import {sample,clone,esc,VERSION,dateLabel,warnings,scriptSections,slides,validateEvent} from './core.js';
import {drawPoster,drawSlide,scriptMarkup,scriptHtml,slideshowHtml} from './render.js';
const KEY='lingnan-forum-workbench-v1';let state={events:[clone(sample)],current:sample.id,history:[]},section='basic',view='poster',slideIndex=0,renderVersion=0,timer,toastTimer;
const $=id=>document.getElementById(id),e=()=>state.events.find(x=>x.id===state.current)||state.events[0];
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4500);}
let startupError='';try{const raw=localStorage.getItem(KEY);if(raw){const p=JSON.parse(raw);if(!Array.isArray(p.events)||!p.events.length||p.events.length>20)throw Error();state={events:p.events.map(validateEvent),current:p.current,history:Array.isArray(p.history)?p.history.slice(-8):[]};if(!state.events.some(x=>x.id===state.current))state.current=state.events[0].id;}}catch{startupError='未能读取本机资料，已打开示例。原保存内容尚未覆盖，请先导出当前工作。';}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('saveStatus').textContent='已保存到本机 '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});}catch{$('saveStatus').textContent='保存失败：请立即导出资料包';toast('浏览器存储不足或不可用。请导出资料包，避免丢失。');}}
function picker(){$('eventPicker').innerHTML=state.events.map(x=>`<option value="${esc(x.id)}"${x.id===state.current?' selected':''}>${esc(x.name)}</option>`).join('');}
const sections=[['basic','基本信息'],['agenda','议程'],['guests','嘉宾'],['org','单位与报名'],['script','主持内容']];
function field(label,key,value,type='text',help=''){return `<label class="field"><span>${esc(label)}</span>${type==='textarea'?`<textarea data-key="${key}">${esc(value)}</textarea>`:`<input type="${type}" data-key="${key}" value="${esc(value)}">`}${help?`<small>${esc(help)}</small>`:''}</label>`;}
function bool(label,key,v){return `<label class="toggle"><input type="checkbox" data-key="${key}"${v?' checked':''}><span>${esc(label)}</span></label>`;}
function tools(kind,i,count){return `<span class="record-tools"><button data-move="${kind}:${i}:-1" aria-label="上移"${i===0?' disabled':''}>↑</button><button data-move="${kind}:${i}:1" aria-label="下移"${i===count-1?' disabled':''}>↓</button><button data-remove="${kind}:${i}">移除</button></span>`;}
function upload(label,key,src,qr=false){return `<label class="field"><span>${label}</span><input type="file" data-image="${key}" accept="image/png,image/jpeg,image/webp">${src?`<img class="${qr?'qr':'photo'}-preview" src="${src}" alt="${label}"><button type="button" data-clear-image="${key}">移除图片</button>`:''}<small>${qr?'上传本场正式二维码，导出后请用手机扫码确认。':'照片只保存在当前浏览器，可随资料包交接。'} 支持PNG、JPEG、WebP，单张不超过2MB。</small></label>`;}
function form(){const x=e();$('sections').innerHTML=sections.map(([k,v])=>`<button data-section="${k}" class="${section===k?'active':''}" aria-pressed="${section===k}">${v}</button>`).join('');let html='';if(section==='basic')html=field('本机活动名称','name',x.name)+field('参访企业','company',x.company)+field('活动标题','title',x.title,'text','修改企业后，请同步确认完整标题。')+field('活动主题','theme',x.theme,'textarea')+`<div class="row">${field('城市','city',x.city)}${field('季节 / 场次','season',x.season)}</div>`+field('活动日期','date',x.date,'date')+field('论坛地点','venue',x.venue)+field('详细地址','address',x.address)+field('签到 / 合影集合点','assembly',x.assembly);
if(section==='agenda'){html='<p class="help">起止时间和环节顺序会同步到三份材料。演讲请选择对应嘉宾，题目从嘉宾资料读取。</p>';html+=x.agenda.map((a,i)=>`<div class="record"><div class="record-head">环节 ${i+1}${tools('agenda',i,x.agenda.length)}</div><div class="row">${field('开始',`agenda.${i}.start`,a.start,'time')}${field('结束',`agenda.${i}.end`,a.end,'time')}</div>${field('环节名称',`agenda.${i}.label`,a.label)}<label class="field"><span>环节类型</span><select data-key="agenda.${i}.kind">${Object.entries({checkin:'签到',visit:'参观',transition:'转场',opening:'开场',talk:'演讲 / 分享',roundtable:'圆桌',qa:'互动',photo:'合影',other:'其他'}).map(([k,v])=>`<option value="${k}"${a.kind===k?' selected':''}>${v}</option>`).join('')}</select></label>${a.kind==='talk'?`<label class="field"><span>对应嘉宾</span><select data-key="agenda.${i}.speaker"><option value="">请选择</option>${x.guests.map(g=>`<option value="${esc(g.id)}"${g.id===a.speaker?' selected':''}>${esc(g.name)}</option>`).join('')}</select></label>`:''}</div>`).join('');html+='<button id="addAgenda">＋ 添加环节</button>';}
if(section==='guests'){html=field('圆桌主题','roundtable',x.roundtable,'textarea');html+=x.guests.map((g,i)=>`<div class="record"><div class="record-head">嘉宾 ${i+1}${tools('guests',i,x.guests.length)}</div>${field('姓名',`guests.${i}.name`,g.name)}${field('正式职务',`guests.${i}.role`,g.role,'textarea')}${field('演讲题目（无演讲可留空）',`guests.${i}.topic`,g.topic,'textarea')}${field('简短介绍',`guests.${i}.bio`,g.bio,'textarea')}${upload('嘉宾照片',`guests.${i}.photo`,g.photo)}${field('圆桌主问题',`guests.${i}.question`,g.question,'textarea')}${field('备用追问',`guests.${i}.followup`,g.followup,'textarea')}</div>`).join('');html+='<button id="addGuest">＋ 添加嘉宾</button>';}
if(section==='org')html=field('指导单位','guidance',x.guidance,'textarea','每行一个单位，按正式排序填写。')+field('主办单位','organizers',x.organizers,'textarea')+field('报名链接','registration',x.registration,'url')+upload('报名二维码','qr',x.qr,true)+field('交通指引','transport',x.transport,'textarea')+field('参加须知','notes',x.notes,'textarea');
if(section==='script'){html=field('主持人','host',x.host)+field('主持人职务','hostRole',x.hostRole,'textarea')+field('到场嘉宾介绍名单','attendees',x.attendees,'textarea','只填已确认的介绍名单。此处不会公开同步。')+field('论坛介绍','forumIntro',x.forumIntro,'textarea')+field('主持人真实案例','personalStory',x.personalStory,'textarea','请填本人真实经历；留空时生成现场提示。')+bool('加入录音及成果整理说明','recording',x.recording)+(x.recording?field('说明文字','recordingText',x.recordingText,'textarea'):'')+bool('加入专委会招募介绍','recruitment',x.recruitment)+(x.recruitment?field('招募介绍','recruitmentText',x.recruitmentText,'textarea'):'')+bool('安排嘉宾致辞','speech',x.speech)+(x.speech?field('致辞人及称谓','speechPerson',x.speechPerson)+field('致辞分钟数','speechMinutes',x.speechMinutes,'number'):'')+field('自定义收尾（留空使用模板）','customClosing',x.customClosing,'textarea')+'<details><summary>逐段润色主持稿</summary><p class="help">润色过的段落将保留，不会被资料更新覆盖。需要同步最新资料时，点击该段“恢复联动”。</p>'+scriptSections(x).map(s=>`<div class="record"><div class="record-head">${esc(s.title)} ${s.custom?'<span>已人工修改</span>':''}</div><textarea data-override="${s.id}" rows="8">${esc(s.text)}</textarea>${s.custom?`<button data-reset="${s.id}">恢复联动</button>`:''}</div>`).join('')+'</details>';}
$('form').innerHTML=html;}
function setPath(path,value){const parts=path.split('.');let o=e();for(const p of parts.slice(0,-1))o=o[p];o[parts.at(-1)]=value;}
function changed(reform=false){save();picker();if(reform)form();clearTimeout(timer);timer=setTimeout(preview,180);}
function download(content,name,type){const url=URL.createObjectURL(content instanceof Blob?content:new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name.replace(/[\\/:*?"<>|]/g,'-');a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
async function preview(){const revision=++renderVersion,x=clone(e());$('eventHeading').textContent=x.title;$('checkCount').textContent=warnings(x).length;$('checks').innerHTML='<strong>待核对项</strong><ul>'+warnings(x).map(s=>`<li>${esc(s)}</li>`).join('')+'</ul>';$('preview').className='preview '+view;$('slideNav').hidden=view!=='slides';document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-selected',b.dataset.view===view));
if(view==='script'){$('preview').innerHTML=scriptMarkup(x);$('outputActions').innerHTML='<button id="downloadScript">下载主持稿 HTML</button><button id="printScript">打印 / PDF</button>';$('previewNote').textContent='主持人稿可在左侧“主持内容”中逐段润色；下载版可离线打开。';return;}
const c=document.createElement('canvas');c.setAttribute('role','img');c.setAttribute('aria-label',view==='poster'?`${x.title}海报预览`:'现场投影预览');if(view==='poster'){await drawPoster(c,x);if(revision!==renderVersion)return;$('outputActions').innerHTML='<button id="downloadPoster" class="primary">下载海报 PNG</button>';$('previewNote').textContent=`${c.width} × ${c.height} 像素 · 沿用蓝色长海报信息顺序；图片中包含待补充提示时请勿对外发布。`;}else{const ss=slides(x);slideIndex=Math.min(slideIndex,ss.length-1);await drawSlide(c,x,ss[slideIndex]);if(revision!==renderVersion)return;$('outputActions').innerHTML='<button id="playSlides">全屏播放</button><button id="downloadSlides" class="primary">下载离线投影</button>';$('slideNumber').textContent=`${slideIndex+1} / ${ss.length} · ${ss[slideIndex].title}`;$('prevSlide').disabled=slideIndex===0;$('nextSlide').disabled=slideIndex===ss.length-1;$('previewNote').textContent='16:9 投影 · 下载后双击HTML可离线播放，支持方向键翻页。嘉宾自带演讲文件需另行准备。';}$('preview').replaceChildren(c);}
async function slidesOutput(open){const win=open?window.open('','_blank'):null;if(open&&!win){toast('弹出窗口被拦截，请允许后重试，或下载离线投影。');return;}if(win){win.document.body.textContent='正在准备投影…';win.opener=null;}const x=clone(e());toast('正在准备离线投影，请稍候…');try{const urls=[];for(const s of slides(x)){const c=document.createElement('canvas');await drawSlide(c,x,s);urls.push(c.toDataURL('image/jpeg',.92));}const html=slideshowHtml(x,urls);if(win){win.document.open();win.document.write(html);win.document.close();}else download(html,x.title+'-现场投影.html','text/html');toast('投影已生成。内容是此刻的版本，后续修改需重新下载。');}catch(err){if(win)win.close();toast('投影导出失败，请重试：'+err.message);}}
function history(){$('history').innerHTML=state.history.filter(h=>h.eventId===e().id).map(h=>`<div><span>${esc(h.time)}</span><button data-restore="${esc(h.id)}">恢复为副本</button></div>`).join('')||'<p class="help">点击“留存版本”，保存当前活动的一个本机快照。</p>';}
function refresh(){picker();form();history();preview();}
document.addEventListener('input',ev=>{const t=ev.target;if(t.dataset.key){setPath(t.dataset.key,t.type==='checkbox'?t.checked:t.value);changed(t.type==='checkbox'||t.tagName==='SELECT');}if(t.dataset.override){e().overrides[t.dataset.override]=t.value;changed();}});
document.addEventListener('change',async ev=>{const t=ev.target;if(t.dataset.image&&t.files[0]){const file=t.files[0];if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024){toast('请上传不超过2MB的PNG、JPEG或WebP图片。');t.value='';return;}try{const im=await createImageBitmap(file);const c=document.createElement('canvas'),max=t.dataset.image==='qr'?900:450,ratio=Math.min(1,max/Math.max(im.width,im.height));c.width=Math.round(im.width*ratio);c.height=Math.round(im.height*ratio);c.getContext('2d').drawImage(im,0,0,c.width,c.height);setPath(t.dataset.image,c.toDataURL(t.dataset.image==='qr'?'image/png':'image/jpeg',.88));im.close();changed(true);}catch{toast('无法读取此图片，请换一张图片。');}}});
document.addEventListener('click',async ev=>{const b=ev.target.closest('button');if(!b)return;try{if(b.dataset.section){section=b.dataset.section;form();}if(b.dataset.view){view=b.dataset.view;preview();}if(b.dataset.move){const[k,i,d]=b.dataset.move.split(':'),a=e()[k],j=Number(i),n=j+Number(d);[a[j],a[n]]=[a[n],a[j]];changed(true);}if(b.dataset.remove){const[k,i]=b.dataset.remove.split(':');if(k==='agenda'&&e().agenda.length===1){toast('至少保留一个活动环节。');return;}if(confirm('移除此项？已关联的内容会提示核对。')){e()[k].splice(Number(i),1);changed(true);}}if(b.dataset.clearImage){setPath(b.dataset.clearImage,'');changed(true);}if(b.dataset.reset){if(confirm('恢复此段与最新资料联动？当前手工文字将被替换。')){delete e().overrides[b.dataset.reset];changed(true);}}if(b.dataset.restore){const h=state.history.find(x=>x.id===b.dataset.restore);if(h){const v=validateEvent(h.event);v.id=crypto.randomUUID();v.name+=' · 恢复副本';state.events.push(v);state.current=v.id;save();refresh();}}switch(b.id){case'addAgenda':if(e().agenda.length>=30)throw Error('最多30个环节');e().agenda.push({start:e().agenda.at(-1)?.end||'14:00',end:'17:30',label:'新环节',kind:'other',speaker:''});changed(true);break;case'addGuest':if(e().guests.length>=12)throw Error('最多12位嘉宾');e().guests.push({id:crypto.randomUUID(),name:'新嘉宾',role:'',topic:'',bio:'',question:'',followup:'',photo:''});changed(true);break;case'duplicate':{if(state.events.length>=20)throw Error('本机最多保留20场，请先导出资料包');const x=clone(e());x.id=crypto.randomUUID();x.name+=' · 新一期';x.attendees='';x.personalStory='';x.qr='';x.registration='';x.overrides={};state.events.push(x);state.current=x.id;save();refresh();toast('已创建独立副本，请修改日期、企业和嘉宾；上一场不受影响。');break;}case'snapshot':state.history.push({id:crypto.randomUUID(),eventId:e().id,time:new Date().toLocaleString('zh-CN'),event:clone(e())});state.history=state.history.slice(-8);save();history();toast('已留存本机版本，最多保留最近8份。');break;case'checksToggle':$('checks').hidden=!$('checks').hidden;break;case'exportData':download(JSON.stringify({schemaVersion:VERSION,event:e()},null,2),e().name+'-资料包.json','application/json');toast('资料包包含当前活动文字及上传图片，请交给指定协作者。');break;case'downloadPoster':{const c=document.createElement('canvas');await drawPoster(c,clone(e()));c.toBlob(blob=>{if(blob)download(blob,e().title+'-海报.png','image/png');else toast('图片导出失败');},'image/png');break;}case'downloadScript':download(scriptHtml(e()),e().title+'-主持稿.html','text/html');break;case'printScript':{const win=window.open('','_blank');if(!win)throw Error('请允许弹出窗口后重试');win.opener=null;win.document.write(scriptHtml(e()));win.document.close();win.focus();setTimeout(()=>win.print(),350);break;}case'downloadSlides':await slidesOutput(false);break;case'playSlides':await slidesOutput(true);break;case'prevSlide':slideIndex=Math.max(0,slideIndex-1);preview();break;case'nextSlide':slideIndex=Math.min(slides(e()).length-1,slideIndex+1);preview();break;}}catch(err){toast(err.message||'操作失败，请重试');}});
$('eventPicker').onchange=()=>{state.current=$('eventPicker').value;slideIndex=0;save();refresh();};
$('importData').onchange=async()=>{try{const f=$('importData').files[0];if(!f)return;if(f.size>12*1024*1024)throw Error('资料包超过12MB');const p=JSON.parse(await f.text());if(p.schemaVersion!==VERSION)throw Error('资料包版本不支持');const x=validateEvent(p.event);if(state.events.length>=20)throw Error('本机最多保留20场');x.id=crypto.randomUUID();x.name+=' · 导入';state.events.push(x);state.current=x.id;save();refresh();toast('已作为独立活动导入，不会覆盖原活动。');}catch(err){toast('导入失败：'+err.message);}finally{$('importData').value='';}};
window.addEventListener('storage',ev=>{if(ev.key===KEY)toast('其他标签页修改了本机资料。请先导出当前资料，再刷新，避免互相覆盖。');});
refresh();if(startupError){$('saveStatus').textContent='原保存资料读取失败';toast(startupError);}else $('saveStatus').textContent='本机资料已加载';
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_forum_draft',title:'读取当前论坛草稿',description:'读取当前本机活动的基础信息和待核对项，不修改资料。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({title:e().title,date:e().date,agenda:clone(e().agenda),warnings:warnings(e())})});}catch{/* optional browser capability */}}

