import {dateLabel,range,agendaLabel,esc,scriptSections} from './core.js';
import {logo} from './brand.js';
const font='"Microsoft YaHei", "PingFang SC", sans-serif';
const images=new Map();
export async function loadImage(src){if(!src)return null;if(images.has(src))return images.get(src);const p=new Promise(resolve=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>resolve(null);im.src=src;});images.set(src,p);return p;}
export function lines(ctx,text,width){const out=[];for(const p of String(text||'').split('\n')){let line='';for(const ch of p){if(ctx.measureText(line+ch).width>width&&line){out.push(line);line=ch;}else line+=ch;}out.push(line);}return out;}
function text(ctx,str,x,y,width,size=30,lineHeight=1.6,align='left',weight='400'){ctx.font=`${weight} ${size}px ${font}`;ctx.textAlign=align;const ls=lines(ctx,str,width);for(const l of ls){ctx.fillText(l,x,y);y+=size*lineHeight;}return y;}
function bg(ctx,w,h){const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'#19007d');g.addColorStop(.5,'#242697');g.addColorStop(1,'#123d9b');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle='#9bb9f015';ctx.lineWidth=2;for(let i=0;i<8;i++){ctx.beginPath();ctx.moveTo(w*.1+i*45,h);ctx.bezierCurveTo(w*.7,h*.85,w*.7,h*.97,w+100,h*.84+i*20);ctx.stroke();}}
export async function drawPoster(canvas,e){await document.fonts.ready;const brand=await loadImage(logo),qr=await loadImage(e.qr);const measure=document.createElement('canvas').getContext('2d');const w=1080,blocks=[];let y=245;function add(s,size=32,align='left',gap=16,weight='400',inset=62){measure.font=`${weight} ${size}px ${font}`;const h=lines(measure,s,w-inset*2).length*size*1.65;blocks.push({s,size,align,y,weight,inset});y+=h+gap;}
add(e.title,44,'center',18,'500');add(e.theme,34,'center',12);add(`（${e.city} · ${e.season}）`,30,'center',25);add('邀请函',38,'center',55);add('活动议程',36,'center',30,'500');for(const a of e.agenda)add(`${a.start}—${a.end}  ${agendaLabel(e,a)}`,29,'left',15);y+=30;add('指导单位',31,'left',8,'500');add(e.guidance,29,'left',30);add('主办单位',31,'left',8,'500');add(e.organizers,29,'left',45);add('时间地点',36,'center',30,'500');add(`时间：${dateLabel(e.date)} ${range(e)}`,29);add(`地点：${e.venue}\n地址：${e.address}\n签到：${e.agenda.find(a=>a.kind==='checkin')?.start||'待确认'}起，${e.assembly}`,29);add(`交通指引：${e.transport}`,27,'left',40);add('注意事项',31,'left',12,'500');add(e.notes,27,'left',35);add(qr?'扫码报名':'报名信息待补充',31,'center',20);if(!qr&&e.registration)add(e.registration,24,'center',10);const qrY=y;y+=qr?400:30;canvas.width=w;canvas.height=Math.ceil(y+85);const ctx=canvas.getContext('2d');bg(ctx,w,canvas.height);if(brand)ctx.drawImage(brand,40,34,430,159);ctx.fillStyle='#ffffff08';ctx.fillRect(22,520,w-44,canvas.height-580);ctx.fillStyle='white';ctx.textBaseline='top';for(const b of blocks)text(ctx,b.s,b.align==='center'?w/2:b.inset,b.y,w-b.inset*2,b.size,1.65,b.align,b.weight);if(qr){ctx.fillStyle='white';ctx.fillRect(350,qrY,380,380);const scale=Math.min(340/qr.width,340/qr.height);ctx.imageSmoothingEnabled=false;ctx.drawImage(qr,540-qr.width*scale/2,qrY+190-qr.height*scale/2,qr.width*scale,qr.height*scale);ctx.imageSmoothingEnabled=true;}return canvas;}
function fitText(ctx,str,x,y,width,maxHeight,size,align='left',min=22){ctx.font=`${size}px ${font}`;while(size>min&&lines(ctx,str,width).length*size*1.65>maxHeight){size-=1;ctx.font=`${size}px ${font}`;}return text(ctx,str,x,y,width,size,1.65,align);}
export async function drawSlide(canvas,e,s){canvas.width=1600;canvas.height=900;const ctx=canvas.getContext('2d');bg(ctx,1600,900);const brand=await loadImage(logo);if(brand)ctx.drawImage(brand,40,28,290,107);ctx.textBaseline='top';ctx.fillStyle='#c8d7ff';text(ctx,`${e.city} · ${e.season}`,1540,45,450,20,1.4,'right');ctx.fillStyle='white';if(s.type==='cover'){fitText(ctx,s.title,800,235,1410,155,62,'center',34);fitText(ctx,s.body,800,425,1320,140,42,'center',26);text(ctx,s.footer||'',800,650,1380,28,1.65,'center');}
else{fitText(ctx,s.title,800,172,1400,110,48,'center');if(s.type==='guest'){const im=await loadImage(s.guest?.photo);if(im){ctx.save();ctx.beginPath();ctx.arc(330,460,125,0,Math.PI*2);ctx.clip();const scale=Math.max(250/im.width,250/im.height);ctx.drawImage(im,330-im.width*scale/2,460-im.height*scale/2,im.width*scale,im.height*scale);ctx.restore();}else{ctx.strokeStyle='#ffffff50';ctx.beginPath();ctx.arc(330,460,115,0,Math.PI*2);ctx.stroke();text(ctx,s.guest?.name||'嘉宾',330,435,230,35,1.4,'center');}fitText(ctx,s.guest?.name||'嘉宾待确认',580,320,850,90,48);fitText(ctx,s.guest?.role||'',580,415,850,130,29);fitText(ctx,s.body,580,585,850,170,35);}
else if(s.type==='roundtable'){fitText(ctx,s.body,800,265,1430,100,35,'center');const gs=s.guests||[],col=1420/Math.max(gs.length,1);for(let i=0;i<gs.length;i++){const g=gs[i],x=90+col*(i+.5),im=await loadImage(g.photo);if(im){ctx.save();ctx.beginPath();ctx.arc(x,455,72,0,7);ctx.clip();const scale=Math.max(144/im.width,144/im.height);ctx.drawImage(im,x-im.width*scale/2,455-im.height*scale/2,im.width*scale,im.height*scale);ctx.restore();}text(ctx,g.name,x,550,col-35,34,1.5,'center');fitText(ctx,g.role,x,615,col-40,130,24,'center',20);}text(ctx,s.footer||'',800,808,1400,25,1.5,'center');}
else{fitText(ctx,s.body,170,325,1260,360,35);if(s.footer)fitText(ctx,s.footer,800,750,1400,80,26,'center');}}return canvas;}
export function scriptMarkup(e){return `<article class="script-paper"><h2>${esc(e.title)} · 主持稿</h2><p class="cue">${esc(dateLabel(e.date))} ${esc(range(e))}<br>${esc(e.venue)}<br>主持人：${esc(e.host)}</p>${scriptSections(e).map(s=>`<section><h3>${esc(s.title)}${s.custom?' · 已人工修改':''}</h3><p class="cue">［${esc(s.cue)}］</p><p>${esc(s.text)}</p></section>`).join('')}</article>`;}
export function scriptHtml(e){return `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(e.title)} 主持稿</title><style>body{font:18px/1.9 'Microsoft YaHei',sans-serif;color:#18264b;max-width:820px;margin:35px auto;padding:20px}h2{font-size:28px}h3{margin-top:35px;font-size:21px}.cue{font-size:14px;color:#66718b}p{white-space:pre-wrap}@media print{body{color:black;font-size:14pt}h3{break-after:avoid}}</style>${scriptMarkup(e)}</html>`;}
export function slideshowHtml(e,urls){return `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(e.title)}</title><style>html,body{margin:0;height:100%;background:#080c22;color:white;font:16px 'Microsoft YaHei',sans-serif}main{height:100%;display:grid;place-items:center}img{max-width:100vw;max-height:100vh;object-fit:contain}nav{position:fixed;bottom:12px;left:50%;transform:translateX(-50%);display:flex;gap:12px;align-items:center;background:#10192ddd;padding:8px 14px;border-radius:8px}button{padding:8px 12px;cursor:pointer;border:0;border-radius:4px}nav:focus-within,nav:hover{opacity:1}nav{opacity:.4}#pages{display:none}@media print{@page{size:landscape;margin:0}main,nav{display:none}#pages{display:block}#pages img{display:block;width:100%;max-height:100vh;break-after:page}}</style><main><img id="slide" alt="论坛投影"></main><nav><button id="prev">上一页</button><span id="n"></span><button id="next">下一页</button><button id="full">全屏</button><button onclick="print()">打印 / PDF</button></nav><div id="pages">${urls.map(u=>`<img src="${u}" alt="投影页">`).join('')}</div><script>const pages=${JSON.stringify(urls)},im=document.getElementById('slide');let i=0;function show(){im.src=pages[i];document.getElementById('n').textContent=(i+1)+' / '+pages.length;document.getElementById('prev').disabled=i===0;document.getElementById('next').disabled=i===pages.length-1}function go(d){i=Math.max(0,Math.min(pages.length-1,i+d));show()}document.getElementById('prev').onclick=()=>go(-1);document.getElementById('next').onclick=()=>go(1);document.getElementById('full').onclick=()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen().catch(()=>{});else document.exitFullscreen()};document.addEventListener('keydown',e=>{if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();go(1)}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(-1)}if(e.key==='Home'){i=0;show()}if(e.key==='End'){i=pages.length-1;show()}});let x=0;document.addEventListener('touchstart',e=>x=e.changedTouches[0].clientX);document.addEventListener('touchend',e=>{let d=e.changedTouches[0].clientX-x;if(Math.abs(d)>70)go(d<0?1:-1)});show();<\/script></html>`;}

